-- Database: GLOBALCIG Metadata version: 2 Exported: Mar 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5731_CERT_VALUES" USING 'GCG_5731_CERT_VALUES.mkd' PAGESIZE=4096 (
 "BOM_PARENT" CHAR(20),
 "PART" CHAR(20),
 "MFG" CHAR(20),
 "MPN" CHAR(20),
 "CUSTOMER" CHAR(10),
 "CUST_PART" CHAR(50),
 "CERT" CHAR(20),
 "DATESTART" DATE,
 "DATEEXP" DATE,
 "C_USER1" CHAR(50),
 "C_USER1_V" CHAR(50),
 "C_USER2" CHAR(50),
 "C_USER2_V" CHAR(50),
 "C_USER3" CHAR(50),
 "C_USER3_V" CHAR(50),
 "C_USER4" CHAR(50),
 "C_USER4_V" CHAR(50),
 "C_USER5" CHAR(50),
 "C_USER5_V" CHAR(50),
 "C_USER6" CHAR(50),
 "C_USER6_V" CHAR(50) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
