-- Database: GLOBALPLA Metadata version: 2 Exported: Feb 13, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5731_VENDOR_CERT" USING 'GCG_5731_VENDOR_CERT.mkd' PAGESIZE=4096 (
 "VENDOR" CHAR(6),
 "VENDOR_NAME" CHAR(30),
 "CERTIFICATION" CHAR(50),
 "DESCRIPTION" CHAR(50),
 "ARC_LIASON" CHAR(50),
 "ARC_EMAIL" CHAR(50),
 "VEND_LIASON" CHAR(50),
 "VEND_PHONE" CHAR(50),
 "VEND_EMAIL" CHAR(50),
 "START_DATE" DATE,
 "END_DATE" DATE,
 "OASIS_NO" CHAR(50),
 "ID_PK" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID_PK" UNIQUE USING 0,
 "VALID" BIT DEFAULT '0' NOT NULL );
-- End Multi-Line Statement
ALTER TABLE "GCG_5731_VENDOR_CERT" ADD CONSTRAINT "PK_ID_PK" PRIMARY KEY  ( "ID_PK" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
